# Generated by Django 4.1.1 on 2022-09-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitespecificsocialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
